services:
  # Servizio per il bot Telegram
  - type: web
    name: crv-rugby-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_fixed.py
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        value: "@CRV_Rugby_Risultati_Partite"
      - key: RENDER
        value: "true"
      - key: RENDER_URL
        value: "https://crv-rugby-bot.onrender.com"

  # Servizio per l'interfaccia web
  - type: web
    name: crv-rugby-web-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_admin.app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: BOT_TOKEN_WEB
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: web_admin/app.py